name: Opam Dependency Submission

on:
  - push
  - pull_request

jobs:
  opam-dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v6

      - name: Set-up OCaml 5.4
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.4
          dune-cache: true
          allow-prerelease-opam: true

      - name: Opam Dependency Submission
        uses: ocaml/setup-ocaml/analysis@v3
